---
title: "SAP - Analiza tržišta nekretnina"
subtitle: "Case study Real estate market analysis"
author: "Adrian Sušec, Josip Goluža, Edi Prodan, Zvonimir Žunić"
date: "28.11.2022."
output: pdf_document
---

# Necesarry libraries

```{r}
library(readr)
library(dplyr)
```

# Loading dataset

```{r}
dataset <- read_csv("preprocessed_data.csv")
```


#Plotting lot shape frequencies

```{r}

dataset %>% 
  group_by(LotShape) %>%
  tally()-> lotshapefreq
lotshapefreq

barplot(lotshapefreq$n, names.arg = lotshapefreq$LotShape, main="Lot shape frequency", xlab="Lot shape type", col="Green")

# radi istu stvar
barplot(table(dataset$LotShape))

```

```{r}
names(dataset)
```

#4. Zadatak
```{r}
houseStyle <- (dataset$HouseStyle)
houseStyle_factor <- factor(houseStyle, levels = unique(houseStyle), labels = c(1, 2, 3, 4,5,6,7,8))
houseStyle
houseStyle_factor
plot(houseStyle_factor, dataset$SalePrice)
dataset$Utilities
```

```{r}
price <- dataset$SalePrice
yearBuilt <- (dataset$YearBuilt)
yearBuilt
fit.date = lm(dataset$SalePrice ~ yearBuilt, data=dataset$SalePrice.data)
fit.date
plot(yearBuilt, dataset$SalePrice)
lines(yearBuilt, fit.date$fitted.values, col="red")
```

```{r}
fit.dates = lm(price ~ yearBuilt + houseStyle_factor, data=dataset$SalePrice.data)
summary(fit.dates)
class(dataset$HouseStyle)
houseStyle <- as.numeric(houseStyle_factor)
class(yearBuilt)
cor(yearBuilt, houseStyle)
```

```{r}
cor(cbind(yearBuilt, houseStyle))

multivars <- c("MSZoning", "Neighborhood", "Condition1", "HouseStyle", "YearBuilt", "Exterior1st", "OverallQual")
df <- data.frame()
df
for (linVar in multivars) {
  if(class(dataset[[linVar]]) == "character") {
    df[linVar] <- factor(dataset[[linVar]], levels = unique(dataset[[linVar]]), labels = c(1:n_distinct(dataset[[linVar]])))
  } else {
    df[linVar] <- dataset[[linVar]]
  }
}
df
```

```{r}
multivars <- c("YearBuilt", "GrLivArea")
df = data.frame(matrix(nrow = 1460, ncol = 2)) 
colnames(df) = multivars

df
for (linVar in multivars) {
    df[linVar] <- dataset[[linVar]]
}
df
cor(df)
```







