---
output:
  pdf_document: default
  html_document: default
---
# Necesarry libraries

```{r}
library(readr)
library(dplyr)
```

# Loading dataset

```{r}
dataset <- read_csv("preprocessed_data.csv")
```

```{r}

plot(dataset$BedroomAbvGr, dataset$SalePrice)

dataset1 = subset(dataset, BedroomAbvGr != 8)

dataset1$ppsqm = dataset1$SalePrice / dataset1$GrLivArea

plot(dataset1$BedroomAbvGr,dataset1$ppsqm)

quartiles = quantile(dataset1$ppsqm, probs = c(.25, .75), na.rm=FALSE)
IQRppsqm = IQR(dataset1$ppsqm)

lower <- quartiles[1] - 1.5*IQRppsqm
upper <- quartiles[2] + 1.5*IQRppsqm

no_outliers = subset(dataset1, dataset1$ppsqm > lower & dataset1$ppsqm < upper)

plot(no_outliers$BedroomAbvGr, no_outliers$ppsqm)

dataset2 <- dataset1[names(dataset1) %in% c('ppsqm', 'BedroomAbvGr')]

no_outliers %>%
  group_by(BedroomAbvGr) %>%
  count() -> dataset3

dataset3

```
```{r}

data1to4 = subset(no_outliers, no_outliers$BedroomAbvGr > 0 & no_outliers$BedroomAbvGr < 5) 

plot(data1to4$ppsqm ~ data1to4$BedroomAbvGr)

boxplot(ppsqm ~ BedroomAbvGr,data=data1to4)
```
```{r}

require(nortest)

bartlett.test(data1to4$ppsqm ~ data1to4$BedroomAbvGr)

lillie.test(data1to4$ppsqm)
lillie.test(data1to4$ppsqm[data1to4$BedroomAbvGr == 1])
lillie.test(data1to4$ppsqm[data1to4$BedroomAbvGr == 2])
lillie.test(data1to4$ppsqm[data1to4$BedroomAbvGr == 3])
lillie.test(data1to4$ppsqm[data1to4$BedroomAbvGr == 4])

aov = aov(data1to4$ppsqm ~ data1to4$BedroomAbvGr)

summary(aov)
```

